version: '3.7'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: flixtallos-api
    ports:
      - 3000:4000
    restart: always
    tty: true
    networks:
      - api-flixtallos
    volumes:
      - .:/home/node/app
networks:
   api-flixtallos:
